config/routes.rb
Rails.application.routes.draw do

  resources :books
  resources :charas
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
end

app/models/chara.rb
class Chara < ApplicationRecord
  validates :name, presence: true
  has_many :chara_weapons, dependent: :destroy

  REALITY_STR = ["R", "SR", "SSR"]
  RACE_STR = ["ヒューマン", "エルーン", "ドラフ", "ハーヴィン", "星晶獣", "不明" ]

  REALITY_OF = {
    :R => 0,
    :SR => 1,
    :SSR => 2
  }

  RACE_OF = {
    :HUMAN => 0,
    :ERUNE => 1,
    :DRAPH => 2,
    :HARVIN => 3,
    :PRIMAL => 4,
    :NONE => 5
  }

  class << self

    def race_groups
      race_groups = {}
      RACE_OF.each_value do |val|
        key = RACE_STR[val]
        race_groups[key] = val
      end
      race_groups
    end

    def reality_groups
      reality_groups = {}
      REALITY_OF.each_value do |val|
        key = REALITY_STR[val]
        reality_groups[key] = val
      end
    end

    def reality_type_of(str)
      res = nil
      REALITY_STR.each_index do |idx|
        if str == REALITY_STR[idx]
          res = idx
        end
      end
      res
    end

    def race_type_of(str)
      res = nil
      RACE_STR.each_index do |idx|
        if str == RACE_STR[idx]
          res = idx
        end
      end
      res
    end

  end


  def race_name
    RACE_STR[self.race]
  end

  def reality_name
    REALITY_STR[self.reality]
  end

  def style_name
    Style.name_of(self.style)
  end

  def element_name
    Element.name_of(self.element)
  end

  def weapon_name
    Weapon.name_of(self.weapon)
  end

  def weapons
    weapons = []
    chara_weapons.each do |idx|
      weapons.push weapon_type_of idx
    end
    weapons
  end
end

app/models/chara_weapon.rb
class CharaWeapon < ApplicationRecord
  belongs_to :chara
end

app/models/element.rb
class Element < ApplicationRecord
  class << self
    def type_of(str)
      Element.find_by(name: str).id rescue nil
    end

    def name_of(id)
      Element.find(id).name rescue nil
    end
  end
end

app/models/style.rb
class Style < ApplicationRecord
  class << self
    def type_of(str)
      Style.find_by(name: str).id rescue nil
    end

    def name_of(id)
      Style.find(id).name rescue nil
    end
  end
end

app/models/weapon.rb
class Weapon < ApplicationRecord
  belongs_to :chara_weapon

  class << self

    def type_of(str)
      Weapon.find_by(name: str).id rescue nil
    end

    def name_of(id)
      Weapon.find(id).name rescue nil
    end

  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.all
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:title, :author_name, :published_on)
    end
end

app/controllers/charas_controller.rb
class CharasController < ApplicationController
  before_action :set_chara, only: [:show, :edit, :update, :destroy]

  def index
    @charas = Chara.all
  end

  # new
  def new
    @chara = Chara.new
    @race_groups = Chara.race_groups
    @reality_groups = Chara.reality_groups

    @style_groups = Style.all.pluck(:name, :id)
    @element_groups = Element.all.pluck(:name, :id)
    @weapon_groups = Weapon.all.pluck(:name, :id)
  end

  def show
  end

  def edit
    @race_groups = Chara.race_groups
    @reality_groups = Chara.reality_groups

    @style_groups = Style.all.pluck(:name, :id)
    @element_groups = Element.all.pluck(:name, :id)
    @weapon_groups = Weapon.all.pluck(:name, :id)
  end

  # create
  def create
    @chara = Chara.new(chara_params)

    respond_to do |format|
      if @chara.save
        format.html { redirect_to @chara, notice: 'Chara was successfullycreated.' }
      else
        format.html { render :new }
      end
    end
  end

  # update
  def update
    respond_to do |format|
      if @chara.update(chara_params)
        format.html { render :show }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @chara.destroy
    respond_to do |format|
      format.html { redirect_to charas_url, notice: 'Chara was successfully destroyed' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chara
      @chara = Chara.find(params[:id])
    end

    def chara_params
      valid_params = [
        :name, :chara_id, :race, :reality, :element, :style, :weapon
      ]
      params.require(:chara).permit(valid_params)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/charas_helper.rb
module CharasHelper
end

app/views/books/_form.html.erb
<%= form_for(book) do |f| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :author_name %>
    <%= f.text_field :author_name %>
  </div>

  <div class="field">
    <%= f.label :published_on %>
    <%= f.date_select :published_on %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Books</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Author name</th>
      <th>Published on</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.author_name %></td>
        <td><%= book.published_on %></td>
        <td><%= link_to 'Show', book %></td>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Book', new_book_path %>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>Author name:</strong>
  <%= @book.author_name %>
</p>

<p>
  <strong>Published on:</strong>
  <%= @book.published_on %>
</p>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

app/views/charas/edit.html.slim
h1 Edit Character

= link_to "Index", charas_path

= form_for @chara do |f|
  dl
    dt= f.label :chara_id, "CharaId"
    dd= f.text_field :chara_id

  dl
    dt= f.label :name
    dd= f.text_field :name

  dl
    dt= f.label :race, "種族"
    dd
      = f.select :race, options_for_select(@race_groups, @chara.race), :include_blank => true

  dl
    dt= f.label :reality, "レアリティ"
    dd
      = f.select :reality, options_for_select(@reality_groups, @chara.reality), :include_blank => true

  dl
    dt= f.label :style, "タイプ"
    dd
      = f.select :style, options_for_select(@style_groups, @chara.style), :include_blank => true

  dl
    dt= f.label :element, "属性"
    dd
      = f.select :element, options_for_select(@element_groups, @chara.element), :include_blank => true
  dl
    dt= f.label :weapon, "得意武器"
    dd
      = f.select :weapon, options_for_select(@weapon_groups, @chara.weapon), :include_blank => true

  .
    = f.submit "Save"

app/views/charas/index.html.slim
h1 Character Index

= link_to 'Add New Character Data', new_chara_path

table
  tr
    th ID
    th Name
    th Reality
    th Style
    th Element
    th Race
    th Weapon
    th colspan="3"
  - @charas.each do |chara|
    tr
      td = chara.id
      td = chara.name
      td = chara.reality_name
      td = chara.style_name
      td = chara.element_name
      td = chara.race_name
      td
        = chara.weapon_name
      td
        = link_to 'Show', chara
      td
        = link_to 'Edit', edit_chara_path(chara)
      td
        = link_to 'Destroy', chara, method: :delete

app/views/charas/new.html.slim
h1 New Character

= link_to "Index", charas_path

- if @chara.errors.any?
  .errors
    ul
      - @chara.errors.full_message.each do |msg|
        li= msg

= form_for @chara do |f|
  dl
    dt= f.label :chara_id, "CharaId"
    dd= f.text_field :chara_id

  dl
    dt= f.label :name
    dd= f.text_field :name

  dl
    dt= f.label :race, "種族"
    dd
      = f.select :race, options_for_select(@race_groups, @chara.race), :include_blank => true

  dl
    dt= f.label :reality, "レアリティ"
    dd
      = f.select :reality, options_for_select(@reality_groups, @chara.reality), :include_blank => true

  dl
    dt= f.label :style, "スタイル"
    dd
      = f.select :style, options_for_select(@style_groups, @chara.style), :include_blank => true

  dl
    dt= f.label :element, "属性"
    dd
      = f.select :element, options_for_select(@element_groups, @chara.element), :include_blank => true
  dl
    dt= f.label :weapon, "得意武器"
    dd
      = f.select :weapon, options_for_select(@weapon_groups, @chara.weapon), :include_blank => true

  .
    = f.submit "Save"

app/views/charas/show.html.slim
h1 Character

= link_to "Index", charas_path

dl
  dt Id
  dd= @chara.id
dl
  dt CharaId
  dd= @chara.chara_id
dl
  dt Name
  dd= @chara.name
dl
  dt Reality
  dd= @chara.reality_name
dl
  dt Style
  dd= @chara.style_name
dl
  dt Element
  dd= @chara.element_name
dl
  dt Race
  dd= @chara.race_name
dl
  dt Weapon
  dd= @chara.weapon_name

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SavaApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>